# general configuration
url: kristiannordestgaard.github.io
# baseurl: '/compass'

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "/images/compass.png"
  # author will appear under the avatar (optional)
  author: "Kristian Nordestgaard"
  # tagline will appear under the title (optional)
  tagline: "Denne side er skabt med <a href='http://jekyllrb.com'>Jekyll</a>/<a href='https://github.com/excentris/compass'>Compass</a>."
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: false

# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: pretty
relative_permalinks: true

# Exclude

exclude [new]
